spring:
  application:
    name: swallow_data_analysis
  text:
    header:
      list: index, first, longitude, latitude
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:mydb.db
    jpa:
      open-in-view: false
      database-platform: org.hibernate.community.dialect.SQLiteDialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.community.dialect.SQLiteDialect
    username: admin
    password: admin
